[package]
name = "_2048_"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "2048"
path = "src/main.rs"

[dependencies]
clap = "2.33.0"
rand = "0.8.0"
